# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/RenameClassifyDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RenameClassifyDialog(object):
    def setupUi(self, RenameClassifyDialog):
        RenameClassifyDialog.setObjectName("RenameClassifyDialog")
        RenameClassifyDialog.resize(342, 194)
        self.verticalLayout = QtWidgets.QVBoxLayout(RenameClassifyDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(RenameClassifyDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.oldNameLineEdit = QtWidgets.QLineEdit(RenameClassifyDialog)
        self.oldNameLineEdit.setObjectName("oldNameLineEdit")
        self.verticalLayout.addWidget(self.oldNameLineEdit)
        self.label_2 = QtWidgets.QLabel(RenameClassifyDialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.newNameLineEdit = QtWidgets.QLineEdit(RenameClassifyDialog)
        self.newNameLineEdit.setObjectName("newNameLineEdit")
        self.verticalLayout.addWidget(self.newNameLineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 14, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(RenameClassifyDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(RenameClassifyDialog)
        self.buttonBox.accepted.connect(RenameClassifyDialog.accept)
        self.buttonBox.rejected.connect(RenameClassifyDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(RenameClassifyDialog)

    def retranslateUi(self, RenameClassifyDialog):
        _translate = QtCore.QCoreApplication.translate
        RenameClassifyDialog.setWindowTitle(_translate("RenameClassifyDialog", "重命名分类"))
        self.label.setText(_translate("RenameClassifyDialog", "原名称"))
        self.label_2.setText(_translate("RenameClassifyDialog", "新名称"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RenameClassifyDialog = QtWidgets.QDialog()
    ui = Ui_RenameClassifyDialog()
    ui.setupUi(RenameClassifyDialog)
    RenameClassifyDialog.show()
    sys.exit(app.exec_())
